# Generated by Django 5.2.5 on 2025-09-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=200)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "meter_type",
                    models.CharField(
                        choices=[
                            ("fiscal", "Fiscal (Billing/Main)"),
                            ("sub", "Submeter"),
                            ("virtual", "Virtual (Computed)"),
                        ],
                        default="sub",
                        max_length=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(help_text="e.g. kWh, m³, kW, °C", max_length=32),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meters",
                        to="api.account",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="api.building",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="api.meter",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="api.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="building",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="api.organization",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="api.organization",
            ),
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(db_index=True)),
                ("value", models.DecimalField(decimal_places=6, max_digits=18)),
                ("unit", models.CharField(max_length=32)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("Actual", "Actual"),
                            ("Estimated", "Estimated"),
                            ("Manual", "Manual"),
                            ("System", "System"),
                        ],
                        default="Actual",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("API", "API"), ("CSV", "CSV"), ("Manual", "Manual")],
                        default="CSV",
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("Accumulated", "Accumulated"),
                            ("Consumption", "Consumption"),
                        ],
                        default="Consumption",
                        max_length=12,
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="api.meter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=4, help_text="0.0–100.0", max_digits=7
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations_in",
                        to="api.meter",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations_out",
                        to="api.meter",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="meter",
            index=models.Index(
                fields=["org", "identifier"], name="api_meter_org_id_81ebd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meter",
            index=models.Index(
                fields=["building"], name="api_meter_buildin_c8bf36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meter",
            index=models.Index(fields=["account"], name="api_meter_account_9f374e_idx"),
        ),
        migrations.AddIndex(
            model_name="meter",
            index=models.Index(
                fields=["meter_type"], name="api_meter_meter_t_53d3d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meter",
            unique_together={("org", "identifier")},
        ),
        migrations.AlterUniqueTogether(
            name="building",
            unique_together={("org", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("org", "name")},
        ),
        migrations.AddIndex(
            model_name="reading",
            index=models.Index(
                fields=["meter", "ts"], name="api_reading_meter_i_f4b81b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reading",
            unique_together={("meter", "ts")},
        ),
        migrations.AlterUniqueTogether(
            name="virtualallocation",
            unique_together={("parent", "child")},
        ),
    ]
