# Generated by Django 5.2.6 on 2025-09-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expression",
                    models.TextField(
                        help_text="Expression DSL, e.g. 'FISCAL - (SUB1 + 0.5*SUB2)'."
                    ),
                ),
                ("start", models.DateTimeField(help_text="Inclusive UTC start.")),
                (
                    "end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Exclusive UTC end; null means open-ended.",
                        null=True,
                    ),
                ),
                (
                    "target_meter",
                    models.ForeignKey(
                        help_text="Must be a virtual meter.",
                        limit_choices_to={"meter_type": "virtual"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulas",
                        to="api.meter",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_meter", "start"],
                        name="api_formula_target__7b944e_idx",
                    ),
                    models.Index(
                        fields=["target_meter", "end"],
                        name="api_formula_target__55a12a_idx",
                    ),
                ],
                "unique_together": {("target_meter", "start", "end")},
            },
        ),
    ]
