# Generated by Django 5.2.6 on 2025-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_formula'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['external_id'], name='api_meter_externa_e3e29d_idx'),
        ),
    ]
